COUNTRIES = {
    (AFGHANISTAN := 'afghanistan') : '🇦🇫',
    (ALBANIA := 'albania') : '🇦🇱',
    (ALGERIA := 'algeria') : '🇩🇿',
    (AMERICAN_SAMOA := 'american_samoa') : '🇦🇸',
    (ANDORRA := 'andorra') : '🇦🇩',
    (ANGOLA := 'angola') : '🇦🇴',
    (ANGUILLA := 'anguilla') : '🇦🇮',
    (ANTARCTICA := 'antarctica') : '🇦🇶',
    (ANTIGUA_AND_BARBUDA := 'antigua_and_barbuda') : '🇦🇬',
    (ARGENTINA := 'argentina') : '🇦🇷',
    (ARMENIA := 'armenia') : '🇦🇲',
    (ARUBA := 'aruba') : '🇦🇼',
    (AUSTRALIA := 'australia') : '🇦🇺',
    (AUSTRIA := 'austria') : '🇦🇹',
    (AZERBAIJAN := 'azerbaijan') : '🇦🇿',
    (BAHAMAS := 'bahamas') : '🇧🇸',
    (BAHRAIN := 'bahrain') : '🇧🇭',
    (BANGLADESH := 'bangladesh') : '🇧🇩',
    (BARBADOS := 'barbados') : '🇧🇧',
    (BELARUS := 'belarus') : '🇧🇾',
    (BELGIUM := 'belgium') : '🇧🇪',
    (BELIZE := 'belize') : '🇧🇿',
    (BENIN := 'benin') : '🇧🇯',
    (BERMUDA := 'bermuda') : '🇧🇲',
    (BHUTAN := 'bhutan') : '🇧🇹',
    (BRAZIL := 'brazil') : '🇧🇷',
    (BRITISH_INDIAN_OCEAN_TERRITORY := 'british_indian_ocean_territory') : '🇮🇴',
    (BRUNEI_DARUSSALAM := 'brunei_darussalam') : '🇧🇳',
    (BOLIVIA := 'bolivia') : '🇧🇴',
    (BOSNIA_AND_HERZEGOVINA := 'bosnia_and_herzegovina') : '🇧🇦',
    (BOTSWANA := 'botswana') : '🇧🇼',
    (BULGARIA := 'bulgaria') : '🇧🇬',
    (BURKINA_FASO := 'burkina_faso') : '🇧🇫',
    (BURUNDI := 'burundi') : '🇧🇮',
    (CAMBODIA := 'cambodia') : '🇰🇭',
    (CAMEROON := 'cameroon') : '🇨🇲',
    (CANADA := 'canada') : '🇨🇦',
    (CAPE_VERDE := 'cape_verde') : '🇨🇻',
    (CAYMAN_ISLANDS := 'cayman_islands') : '🇰🇾',
    (CHILE := 'chile') : '🇨🇱',
    (CHINA := 'china') : '🇨🇳',
    (CHRISTMAS_ISLAND := 'christmas_island') : '🇨🇽',
    (COCOS_ISLANDS := 'cocos_islands') : '🇨🇨',
    (COLOMBIA := 'colombia') : '🇨🇴',
    (COMOROS := 'comoros') : '🇰🇲',
    (CONGO := 'congo') : '🇨🇬',
    (COOK_ISLANDS := 'cook_islands') : '🇨🇰',
    (COSTA_RICA := 'costa_rica') : '🇨🇷',
    (COTE_DIVOIRE := 'cote_divoire') : '🇨🇮',
    (CROATIA := 'croatia') : '🇭🇷',
    (CUBA := 'cuba') : '🇨🇺',
    (CYPRUS := 'cyprus') : '🇨🇾',
    (CZECH_REPUBLIC := 'czech_republic') : '🇨🇿',
    (DENMARK := 'denmark') : '🇩🇰',
    (DJIBOUTI := 'djibouti') : '🇩🇯',
    (DOMINICAN_REPUBLIC := 'dominican_republic') : '🇩🇴',
    (ECUADOR := 'ecuador') : '🇪🇨',
    (EGYPT := 'egypt') : '🇪🇬',
    (EQUATORIAL_GUINEA := 'equatorial_guinea') : '🇬🇶',
    (EL_SALVADOR := 'el_salvador') : '🇸🇻',
    (EUROPE := 'europe') : '🇪🇺',
    (EUROPEAN_UNION := 'european_union') : '🇪🇺',
    (FALKLAND_ISLANDS := 'falkland_islands') : '🇫🇰',
    (FIJI := 'fiji') : '🇫🇯',
    (FINLAND := 'finland') : '🇫🇮',
    (FRANCE := 'france') : '🇫🇷',
    (FRENCH_GUIANA := 'french_guiana') : '🇬🇫',
    (FRENCH_POLYNESIA := 'french_polynesia') : '🇵🇫',
    (FRENCH_SOUTHERN_TERRITORIES := 'french_southern_territories') : '🇹🇫',
    (GABON := 'gabon') : '🇬🇦',
    (GAMBIA := 'gambia') : '🇬🇲',
    (GEORGIA := 'georgia') : '🇬🇪',
    (GERMANY := 'germany') : '🇩🇪',
    (GUATEMALA := 'guatemala') : '🇬🇹',
    (HONDURAS := 'honduras') : '🇭🇳',
    (ITALY := 'italy') : '🇮🇹',
    (JAPAN := 'japan') : '🇯🇵',
    (KOREA := 'korea') : '🇰🇷',
    (MEXICO := 'mexico') : '🇲🇽',
    (MOROCCO := 'morocco') : '🇲🇦',
    (NETHERLANDS := 'netherlands') : '🇳🇱',
    (NEW_ZEALAND := 'new_zealand') : '🇳🇿',
    (NIGERIA := 'nigeria') : '🇳🇬',
    (PANAMA := 'panama') : '🇵🇦',
    (PARAGUAY := 'paraguay') : '🇵🇾',
    (PERU := 'peru') : '🇵🇪',
    (PHILIPPINES := 'philippines') : '🇵🇭',
    (POLAND := 'poland') : '🇵🇱',
    (PORTUGAL := 'portugal') : '🇵🇹',
    (PUERTO_RICO := 'puerto_rico') : '🇵🇷',
    (QATAR := 'qatar') : '🇶🇦',
    (ROMANIA := 'romania') : '🇷🇴',
    (RUSSIA := 'russia') : '🇷🇺',
    (RWANDA := 'rwanda') : '🇷🇼',
    (SAUDI_ARABIA := 'saudi_arabia') : '🇸🇦',
    (SENEGAL := 'senegal') : '🇸🇳',
    (SERBIA := 'serbia') : '🇷🇸',
    (SEYCHELLES := 'seychelles') : '🇸🇨',
    (SIERRA_LEONE := 'sierra_leone') : '🇸🇱',
    (SINGAPORE := 'singapore') : '🇸🇬',
    (SLOVAKIA := 'slovakia') : '🇸🇰',
    (SLOVENIA := 'slovenia') : '🇸🇮',
    (SOUTH_AFRICA := 'south_africa') : '🇿🇦',
    (SOUTH_KOREA := 'south_korea') : '🇰🇷',
    (SPAIN := 'spain') : '🇪🇸',
    (SUDAN := 'sudan') : '🇸🇩',
    (SURINAME := 'suriname') : '🇸🇷',
    (SWEDEN := 'sweden') : '🇸🇪',
    (SWITZERLAND := 'switzerland') : '🇨🇭',
    (TAIWAN := 'taiwan') : '🇹🇼',
    (TURKEY := 'turkey') : '🇹🇷',
    (UKRAINE := 'ukraine') : '🇺🇦',
    (UNITED_STATES := 'united_states') : '🇺🇸',
    (UK := 'uk') : '🇬🇧',
    (UNITED_KINGDOM := 'united_kingdom') : '🇬🇧',
    (URUGUAY := 'uruguay') : '🇺🇾',
    (VANUATU := 'vanuatu') : '🇻🇺',
    (VENEZUELA := 'venezuela') : '🇻🇪',
    (VIETNAM := 'vietnam') : '🇻🇳',
    (ZAMBIA := 'zambia') : '🇿🇲',
    (ZIMBABWE := 'zimbabwe') : '🇿🇼',
    (WORLD := 'world') : '🌎',
}

ARROWS = {
    (ARROW_LEFT_BOLD := 'arrow_left_bold') : '⬅',
    (ARROW_RIGHT_BOLD := 'arrow_right_bold') : '➡',
    (ARROW_UP_BOLD := 'arrow_up_bold') : '⬆',
    (ARROW_DOWN_BOLD := 'arrow_down_bold') : '⬇',
    (ARROW_RIGHT_UP_BOLD := 'arrow_right_up_bold') : '⬈',
    (ARROW_LEFT_UP_BOLD := 'arrow_left_up_bold') : '⬉',
    (ARROW_RIGHT_DOWN_BOLD := 'arrow_right_down_bold') : '⬊',
    (ARROW_LEFT_DOWN_BOLD := 'arrow_left_down_bold') : '⬋',
    (ARROW_LEFT_RIGHT_BOLD := 'arrow_left_right_bold') : '⬌',
    (ARROW_UP_DOWN_BOLD := 'arrow_up_down_bold') : '⬍',
    (ARROW_LEFT_RIGHT := 'arrow_left_right') : '↔',
    (ARROW_UP_DOWN := 'arrow_up_down') : '↕',
    (ARROW_UP := 'arrow_up') : '↑',
    (ARROW_DOWN := 'arrow_down') : '↓',
    (ARROW_LEFT := 'arrow_left') : '←',
    (ARROW_RIGHT := 'arrow_right') : '→',
    (ARROW_LEFT_UP := 'arrow_left_up') : '↖',
    (ARROW_LEFT_DOWN := 'arrow_left_down') : '↙',
    (ARROW_RIGHT_UP := 'arrow_right_up') : '↗',
    (ARROW_RIGHT_DOWN := 'arrow_right_down') : '↘',
    (DOBLE_ARROW_RIGHT := 'doble_arrow_right') : '⇉',
    (DOBLE_ARROW_LEFT := 'doble_arrow_left') : '⇇',
    (DOBLE_ARROW_UP := 'doble_arrow_up') : '⇈',
    (DOBLE_ARROW_DOWN := 'doble_arrow_down') : '⇊',
    (DOBLE_ARROW_LEFT_RIGHT := 'doble_arrow_left_right') : '⇄',
    (DOBLE_ARROW_UP_DOWN := 'doble_arrow_up_down') : '⇅',
    (ARROW_DOWN_DASHED := 'arrow_down_dashed') : '⇣',
    (ARROW_LEFT_DASHED := 'arrow_left_dashed') : '⇠',
    (ARROW_UP_DASHED := 'arrow_up_dashed') : '⇡',
    (ARROW_RIGHT_DASHED := 'arrow_right_dashed') : '⇢',
    (ARROW_RIGHT_WHITE := 'arrow_right_white') : '⇨',
    (ARROW_UP_WHITE := 'arrow_up_white') : '⇧',
    (ARROW_DOWN_WHITE := 'arrow_down_white') : '⇩',
    (ARROW_LEFT_WHITE := 'arrow_left_white') : '⇦',
    (ARROW_UP_DOWN_WHITE := 'arrow_up_down_white') : '⇳',
    (ARROW_UP_WHITE_FROM_BAR := 'arrow_up_white_from_bar') : '⇪',
    (ARROW_UP_WHITE_PEDESTAL := 'arrow_down_white_pedestal') : '⇫',
}

PEOPLE = {
    (SMILE := 'smile') : '😄',
    (BLUSH := 'blush') : '😊',
    (SMILE_WITH_HEART := 'smile_with_heart') : '😍',
    (SMILE_WITH_SUNGLASSES := 'smile_with_sunglasses') : '😎',
    (WINK := 'wink') : '😉',
    (LOL := 'lol') : '😂',
    (WOW := 'wow') : '😮',
    (SAD := 'sad') : '😢',
    (ANGRY := 'angry') : '😠',
    (THINKING := 'thinking') : '🤔',
    (FLUSH := 'flush') : '😳',
    (CRY := 'cry') : '😭',
    (CONFUSED := 'confused') : '😕',
    (LAUGH := 'laugh') : '😆',
    (YUM := 'yum') : '😋',
    (SMIRK := 'smirk') : '😏',
    (SCREAM := 'scream') : '😱',
    (CAT := 'cat') : '😺',
    (DOG := 'dog') : '🐶',
    (MOUTH := 'mouth') : '👄',
    (TONGUE := 'tongue') : '👅',
    (WINKING_FACE := 'winking_face') : '😜',
    (PENSIVE_FACE := 'pensive_face') : '😔',
    (UNAMUSED_FACE := 'unamused_face') : '😒',
    (KISSING_HEART := 'kissing_heart') : '😘',
    (KISSING_CLOSED_EYES := 'kissing_closed_eyes') : '😚',
    (KISSING := 'kissing') : '😗',
    (COLD_SWEAT := 'cold_sweat') : '😰',
    (HOT_FACE := 'hot_face') : '🥵',
    (GRIMARCING := 'grimacing') : '🤐',
    (STUCK_OUT_TONGUE := 'stuck_out_tongue') : '😛',
    (STUCK_OUT_TONGUE_CLOSED_EYE := 'stuck_out_tongue_closed_eye') : '😝',
    (SKULL := 'SKULL') : '💀',
    (SKULL_AND_CROSSBONES := 'skull_and_crossbones') : '☠',
    (CLOWN := 'clown') : '🤡',
    (POOP := 'poop') : '💩',
    (JAPANESE_OGRE := 'japanese_ogre') : '👹',
    (JAPANESE_GOBLIN := 'japanese_goblin') : '👺',
    (GHOST := 'ghost') : '👻',
    (SWEAT := 'sweat') : '😓',
    (DIZZY := 'dizzy') : '😵',
    (ALIEN := 'alien') : '👽',
    (IMP := 'imp') : '👿',
    (SMILING_IMP := 'smiling_imp') : '😈',
    (HEART := 'heart') : '❤',
    (HEART_BIG := 'heart_big') : '💗',
    (HEART_BROKEN := 'heart_broken') : '💔',
    (TWO_HEART := 'two_heart') : '💕',
    (PURPLE_HEART := 'purple_heart') : '💜',
    (BLUE_HEART := 'blue_heart') : '💙',
    (GREEN_HEART := 'green_heart') : '💚'
}

ALL_EMOJIS = {

    **COUNTRIES,
    **ARROWS,
    **PEOPLE,

    (WARNING := 'warning') : '⚠',
    (ERROR   := 'error')   : '❌',
    (SUCCESS := 'success') : '✅',
    (INFO := 'info')    : '💡',
    (QUESTION := 'question') : '❓',
    (ANSWER := 'answer') : '💬',
    (HEART := 'heart') : '❤',
    (STAR := 'star') : '⭐',
    (CIRCLE := 'circle') : '⚪',
    (CROSS := 'cross') : '❌',
    (CHECK := 'check') : '✔',
    (SPARKLES := 'sparkles') : '✨',

    (TRIANGLE_RIGHT := 'triangle_right') : '▶',
    (TRIANGLE_LEFT := 'triangle_left') : '◀',
    (TRIANGLE_UP := 'triangle_up') : '▲',
    (TRIANGLE_DOWN := 'triangle_down') : '▼',
}

EMOJIS_LIST = list(ALL_EMOJIS.keys())


def emoji(icon: str) -> str:
    """
    Return the icon of the given name

    Parameters
    ----------
    icon : str
        The name of the icon to return
    """
    return ALL_EMOJIS[icon] if icon in EMOJIS_LIST else ''
